### PR TITLE
Separate config/data and software

### PR DESCRIPTION
**Pull request by ParFlesh**
This is probably a bit of a far reach, but if it is welcome here is what I did to separate the configuration and data from the software.

* Store all persistent data in MCVOLUME (/config)
* Join curl, unzip, and rm of zip (saves ~49MB)
* A little more cleanup after apt install (saves ~27MB)
* Create configuration files from default if they do not exist
* Link config files on startup
* Change user to non-root (little more secure and allows running on secured environments)
* Generate configuration from environment variables
* Change ENTRYPOINT directive to CMD (Allows changes to command on run)

### CODE REVIEW

**Comment by ParFlesh** [comment]
Also added exec to pass pid 1 to bedrock_server binary, so all term signals go to server instead of startup.sh

**Comment by karlrees** [comment]
This looks great.  I must admit that I just hacked my version together quickly to get something up and running for the kids, without much concern about the proper way to do things.  I'll find some time to test in the next few days.

**Comment by ParFlesh** [comment]
It was the best I found when I started looking.    
    
I just wanted to be able to run it on an Openshift cluster.

**Comment by karlrees** [comment]
Looks good for the most part.  But I'd like to add some code, mostly for backwards compatibility, so I'm pulling it to a beta branch for now.  Some questions:

1) I assume you're either running only one server, or sharing permissions.json, etc. between all of your servers?  I have a number of different worlds, each with their own permissions.json.  To handle this, I'm thinking that the startup.sh script should first search for a $WORLD.xxx file or directory (e.g. $WORLD.permissions.json) and link to that, or if none can be found, then fall back to your code.  What do you think?

2) You've chosen 1001:0 as the default user ID / group.  Any particular reason?  Would 1000:1000 be a better choice?  I really have no idea, just curious.

3) Any particular reason you chose to go with using environment variables instead of just copying server.properties file?  I think I like the idea, but for backwards compatibility, I think I'm going to search for a $WORLD.server.properties file first, then fall back to your code.

**Comment by ParFlesh** [comment]
1.  Yes, I only expected to run one server/world.  Each additional server/world would have been another container running with a separate volume.  I didn't think about running multiple servers from one volume.  Yeah, shouldn't be much work to check for $WORLD.<file> then fall back to <file> for all of the files.
    
2.  I went with 1001:0 because that is what I am used to.  Openshift defaults to a random UID and GID 0, but any UID/GID combination should work.
    
3. Generating the server.properties allowed me to preconfigure the world seed before start without having to create the file.  I think I can work up a little more bash to check for $WORLD.<file> then <file> for all items then use that.

**Comment by karlrees** [comment]
I had already worked out the code to check for $WORLD files.  I just pushed that and a few other updates to the beta branch.  Still testing it, but feel free to have a look.

**Comment by karlrees** [comment]
Hey, @ParFlesh, what do you think about making the default MCVOLUME something like "mcdata" instead of "config"?  Seems like it might be a bit more descriptive.

**Comment by ParFlesh** [comment]
Sounds good to me.  I also found that the server is not shutting down gracefully, so I will create a pr for that.

**Pull request merged**
